apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hasher-rs
  
spec:
  replicas: 2
  
  selector:
    matchLabels:
      application: "hasher"
      
  template:
    metadata:
      labels: 
        application: "hasher"
    spec: 
      containers:
        - image: charleslowery/simplilearn-dockercoins:hasher-latest 
          name: hasher-container
          ports:
            - containerPort: 8080
