apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hasher-rs
  labels:
    enviroment: ruby
    description: Produces a SHA2 hash given a integer seed
  
spec:
  replicas: 2
  selector:
    matchLabels:
      hasher: true
  template: 
    metadata:
      labels: 
        hasher: true
    spec: 
      containers:
        - image: charleslowery/simplilearn-dockercoins:hasher-latest 
          name: hasher-container
