apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: redis-rs
  
spec:
  replicas: 1
  selector:
    matchLabels:
      application: "redis"
  template: 
    metadata:
      labels: 
        application: "redis"
    spec: 
      containers:
        -
          image: redis:alpine
          name: redis-container
          ports: 
            - containerPort: 6379
          volumeMounts: 
            -
              mountPath: /data
              name: redis-volume
      volumes:
        -
          emptyDir:
          name: redis-volume
