apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: rng-rs
  
spec:
  replicas: 2
  selector:
    matchLabels:
      application: "rng"
  template: 
    metadata:
      labels: 
        application: "rng"
    spec: 
      containers:
        -
          image: charleslowery/simplilearn-dockercoins:rng-latest 
          name: rng-container
