################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
name: ci

on:
  push:
    branches:
      - docker
      
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: Setup Enviroment
        run: |
          sh scripts/environment.sh
      -
        name: test
        run: |
          while true
            do
              sleep 10
             docker logs worker 2>& 1 | grep "Coin found" && break
            done
